### ISSUE TITLE
[PE-D] Exit Command seems broken, maybe just delete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-TIC4002-F18-3/tp2#80]
```
exit
```
seems not working at all, nothing happened.

Maybe delete it in UG?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: l-shihao/ped#5

**Comment by yinyin377** [comment]
I have tested on my end, `exit` does close the application.

**Comment by l-shihao** [comment]
weird, seems working now
